### PR TITLE
apply changes to build the app for focal

### PR DESCRIPTION
**Pull request by Danfro**
With those changes the app can be build for focal and does work. I haven't tested all features though.

Of course would be great to get a newer version of cinny packaged. But I have no idea how to do that.

### CODE REVIEW

**Comment by JamiKettunen** [comment]
`clickable -a arm64` fails for me using `clickable` v7.11.0 with `podman` as container backend:
```
-- Configuring done
CMake Error at libs/qhttp/CMakeLists.txt:32 (add_library):
  Cannot find source file:

    ../http-parser/http_parser.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Command exited with non-zero exit status 1, see above for details. This is most likely not a problem with Clickable.
```
(full build log: https://termbin.com/v8bi)

**Comment by JamiKettunen** [comment]
Ignore my above comment, I realized this repo uses [git submodules](https://github.com/nitanmarcel/cinny-click-packaging/blob/main/.gitmodules) (ugh)

**Comment by nitanmarcel** [comment]
Thabks for the PR. 

Will merge it since should most likely work, unless for some reason cinny doesn't like something in 20.04.

**Comment by JamiKettunen** [comment]
@nitanmarcel Remember to push a `focal` version to https://open-store.io/app/cinny.nitanmarcel :)

**Comment by nitanmarcel** [comment]
> @nitanmarcel Remember to push a `focal` version to https://open-store.io/app/cinny.nitanmarcel :)

Yep, done it right now

https://open-store.io/app/cinny.nitanmarcel

**Pull request merged**
